# Generated by Django 5.2.4 on 2025-07-16 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order_signup_product_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='interval_months',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stripe_price_id',
        ),
        migrations.CreateModel(
            name='StripePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_price_id', models.CharField(max_length=255, unique=True)),
                ('recurring_interval', models.PositiveIntegerField(blank=True, null=True)),
                ('one_time', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_prices', to='shop.product')),
            ],
            options={
                'unique_together': {('product', 'recurring_interval', 'one_time')},
            },
        ),
    ]
